### ISSUE TITLE
Error running make

### ISSUE THREAD

**Issue by ksasa001** [kit-cel/gr-radar#10]
```
[ 42%] Building CXX object lib/CMakeFiles/gnuradio-radar.dir/usrp_echotimer_cc_impl.cc.o
/home/korysasaoka/Documents/gr-radar/lib/usrp_echotimer_cc_impl.cc: In member function ‘void gr::radar::usrp_echotimer_cc_impl::receive()’:
/home/korysasaoka/Documents/gr-radar/lib/usrp_echotimer_cc_impl.cc:232:16: error: ‘class uhd::rx_streamer’ has no member named ‘issue_stream_cmd’
   d_rx_stream->issue_stream_cmd(stream_cmd);
                ^
/home/korysasaoka/Documents/gr-radar/lib/usrp_echotimer_cc_impl.cc:245:84: error: ‘struct uhd::rx_metadata_t’ has no member named ‘strerror’
    throw std::runtime_error(str(boost::format("Receiver error %s") % d_metadata_rx.strerror()));
                                                                                    ^
/home/korysasaoka/Documents/gr-radar/lib/usrp_echotimer_cc_impl.cc:245:94: error: ‘str’ was not declared in this scope
    throw std::runtime_error(str(boost::format("Receiver error %s") % d_metadata_rx.strerror()));
                                                                                              ^
/home/korysasaoka/Documents/gr-radar/lib/usrp_echotimer_cc_impl.cc:245:94: note: suggested alternatives:
In file included from /usr/include/boost/format.hpp:53:0,
                 from /usr/local/include/gnuradio/logger.h:57,
                 from /usr/local/include/gnuradio/block.h:29,
                 from /usr/local/include/gnuradio/tagged_stream_block.h:27,
                 from /home/korysasaoka/Documents/gr-radar/include/radar/usrp_echotimer_cc.h:25,
                 from /home/korysasaoka/Documents/gr-radar/lib/usrp_echotimer_cc_impl.h:24,
                 from /home/korysasaoka/Documents/gr-radar/lib/usrp_echotimer_cc_impl.cc:26:
/usr/include/boost/format/free_funcs.hpp:22:38: note:   ‘boost::str’
     std::basic_string<Ch, Tr, Alloc> str(const basic_format<Ch, Tr, Alloc>& f) {
                                      ^
/usr/include/boost/format/free_funcs.hpp:22:38: note:   ‘boost::str’
make[2]: *** [lib/CMakeFiles/gnuradio-radar.dir/usrp_echotimer_cc_impl.cc.o] Error 1
make[1]: *** [lib/CMakeFiles/gnuradio-radar.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by stwunsch** [comment]
Hi, I assume that your BOOST version doesn't met the required dependency. Check this and write again, if this does not work.

**Comment by pelsor** [comment]
hi,I have get the same error,have you solved it ,please let me know.

**Comment by stwunsch** [comment]
Hi,
The error occurs due to a too old boost version. Have you checked yours?

**Comment by stwunsch** [comment]
I've checked it, it runs with:
- gnuradio 3.7.9.1
- uhd 3.9.2
- boost 1.60.0

**Comment by pelsor** [comment]
hi, I have update my boost version to boost **Boost version: 1.60.0**,but I still get the error when I make,here is my issue:

[ 42%] Building CXX object lib/CMakeFiles/gnuradio-radar.dir/usrp_echotimer_cc_impl.cc.o
/home/mhf/gr-radar-master/lib/usrp_echotimer_cc_impl.cc: In member function ‘void gr::radar::usrp_echotimer_cc_impl::receive()’:
/home/mhf/gr-radar-master/lib/usrp_echotimer_cc_impl.cc:232:16: error: ‘class uhd::rx_streamer’ has no member named ‘issue_stream_cmd’
   d_rx_stream->issue_stream_cmd(stream_cmd);
                ^
/home/mhf/gr-radar-master/lib/usrp_echotimer_cc_impl.cc:245:84: error: ‘struct uhd::rx_metadata_t’ has no member named ‘strerror’
    throw std::runtime_error(str(boost::format("Receiver error %s") % d_metadata_rx.strerror()));
                                                                                    ^
/home/mhf/gr-radar-master/lib/usrp_echotimer_cc_impl.cc:245:94: error: ‘str’ was not declared in this scope
    throw std::runtime_error(str(boost::format("Receiver error %s") % d_metadata_rx.strerror()));
                                                                                              ^
/home/mhf/gr-radar-master/lib/usrp_echotimer_cc_impl.cc:245:94: note: suggested alternatives:
In file included from /usr/local/include/boost/format.hpp:53:0,
                 from /usr/local/include/gnuradio/logger.h:55,
                 from /usr/local/include/gnuradio/block.h:29,
                 from /usr/local/include/gnuradio/tagged_stream_block.h:27,
                 from /home/mhf/gr-radar-master/include/radar/usrp_echotimer_cc.h:25,
                 from /home/mhf/gr-radar-master/lib/usrp_echotimer_cc_impl.h:24,
                 from /home/mhf/gr-radar-master/lib/usrp_echotimer_cc_impl.cc:26:
/usr/local/include/boost/format/free_funcs.hpp:22:38: note:   ‘boost::str’
     std::basic_string<Ch, Tr, Alloc> str(const basic_format<Ch, Tr, Alloc>& f) {
                                      ^
/usr/local/include/boost/format/free_funcs.hpp:22:38: note:   ‘boost::str’
make[2]: *** [lib/CMakeFiles/gnuradio-radar.dir/usrp_echotimer_cc_impl.cc.o] 错误 1
make[1]: *** [lib/CMakeFiles/gnuradio-radar.dir/all] 错误 2
make: *** [all] 错误 2

and here is my info when I cmake ..:

mhf@mhf-laptop:~/gr-radar-master/build$ cmake ..
-- The CXX compiler identification is GNU 4.8.5
-- The C compiler identification is GNU 4.8.5
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Build type not specified: defaulting to release.
-- Boost version: 1.60.0
-- Found the following Boost libraries:
--   filesystem
--   system
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.26") 
-- checking for module 'cppunit'
--   found cppunit, version 1.13.1
-- Found CPPUNIT: /usr/lib/x86_64-linux-gnu/libcppunit.so;dl  
-- checking for module 'fftw3f >= 3.0'
--   found fftw3f , version 3.3.3
-- Found FFTW3F: /usr/lib/x86_64-linux-gnu/libfftw3f.so  
-- Looking for Q_WS_X11
-- Looking for Q_WS_X11 - found
-- Looking for Q_WS_WIN
-- Looking for Q_WS_WIN - not found
-- Looking for Q_WS_QWS
-- Looking for Q_WS_QWS - not found
-- Looking for Q_WS_MAC
-- Looking for Q_WS_MAC - not found
-- Found Qt4: /usr/local/Trolltech/Qt-4.8.6/bin/qmake (found suitable version "4.8.6", minimum required is "4.2.0") 
-- QWT Version: 6.0.0
-- Found Qwt: /usr/local/lib/libqwt.so  
-- checking for module 'uhd'
--   found uhd, version 003.005.002-0-unknown
-- Found UHD: /usr/local/lib/libuhd.so  
Checking for GNU Radio Module: RUNTIME
-- checking for module 'gnuradio-runtime'
--   found gnuradio-runtime, version 3.7.5
 * INCLUDES=/usr/local/include
 * LIBS=/usr/local/lib/libgnuradio-runtime.so;/usr/local/lib/libgnuradio-pmt.so
-- Found GNURADIO_RUNTIME: /usr/local/lib/libgnuradio-runtime.so;/usr/local/lib/libgnuradio-pmt.so  
GNURADIO_RUNTIME_FOUND = TRUE
-- Found SWIG: /usr/bin/swig2.0 (found version "2.0.11") 
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython2.7.so (found suitable version "2.7.6", minimum required is "2") 
-- Found PythonInterp: /usr/bin/python2 (found suitable version "2.7.6", minimum required is "2") 
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of size_t
-- Check size of size_t - done
-- Check size of unsigned int
-- Check size of unsigned int - done
-- Performing Test HAVE_WNO_UNUSED_BUT_SET_VARIABLE
-- Performing Test HAVE_WNO_UNUSED_BUT_SET_VARIABLE - Success
-- Configuring done
-- Generating done
-- Build files have been written to: /home/mhf/gr-radar-master/build

I think my gnuradio or my uhd version not right ,do you think so? please tell me where I'm wrong?thanks!!!

**Comment by stwunsch** [comment]
Hi,


-- checking for module 'uhd'
-- found uhd, version 003.005.002-0-unknown
-- Found UHD: /usr/local/lib/libuhd.so

You are running UHD 3.5.2, try a minimum of UHD 3.7.2 (as written in the
dependencies). The up-to-date version is UHD 3.9.2.

Best regards
Stefan

**Comment by marcusmueller** [comment]
That UHD version is **ancient**. Update UHD. 3.5.2 is really nothing anyone should still be supporting these days.

**Comment by pelsor** [comment]
hi,I have updated boost version to** boost 1.60.0**,and change my gnuradio version to **gnuradio 3.7.9.1** and my uhd version to **uhd 3.10.0**,and i successfuly installed the gr-radar.thankyou very much !!!
