### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by pelsor** [kit-cel/gr-radar#12]
HI,guys! I get an error when I **make** the gr-radar at **75%**,here is my make log: 
[  1%] Generating moc_spectrogram_plot.cxx
[  3%] Generating moc_scatter_plot.cxx
[  5%] Generating moc_time_plot.cxx
Scanning dependencies of target gnuradio-radar
[  7%] Building CXX object lib/CMakeFiles/gnuradio-radar.dir/moc_scatter_plot.cxx.o
[  9%] Building CXX object lib/CMakeFiles/gnuradio-radar.dir/moc_time_plot.cxx.o
[ 11%] Building CXX object lib/CMakeFiles/gnuradio-radar.dir/moc_spectrogram_plot.cxx.o
[ 13%] Building CXX object lib/CMakeFiles/gnuradio-radar.dir/scatter_plot.cc.o
[ 15%] Building CXX object lib/CMakeFiles/gnuradio-radar.dir/time_plot.cc.o
[ 17%] Building CXX object lib/CMakeFiles/gnuradio-radar.dir/spectrogram_plot.cc.o
[ 19%] Building CXX object lib/CMakeFiles/gnuradio-radar.dir/signal_generator_cw_c_impl.cc.o
[ 21%] Building CXX object lib/CMakeFiles/gnuradio-radar.dir/signal_generator_fmcw_c_impl.cc.o
[ 23%] Building CXX object lib/CMakeFiles/gnuradio-radar.dir/split_cc_impl.cc.o
[ 25%] Building CXX object lib/CMakeFiles/gnuradio-radar.dir/os_cfar_c_impl.cc.o
[ 26%] Building CXX object lib/CMakeFiles/gnuradio-radar.dir/ts_fft_cc_impl.cc.o
[ 28%] Building CXX object lib/CMakeFiles/gnuradio-radar.dir/estimator_cw_impl.cc.o
[ 30%] Building CXX object lib/CMakeFiles/gnuradio-radar.dir/print_results_impl.cc.o
[ 32%] Building CXX object lib/CMakeFiles/gnuradio-radar.dir/static_target_simulator_cc_impl.cc.o
[ 34%] Building CXX object lib/CMakeFiles/gnuradio-radar.dir/signal_generator_fsk_c_impl.cc.o
[ 36%] Building CXX object lib/CMakeFiles/gnuradio-radar.dir/split_fsk_cc_impl.cc.o
[ 38%] Building CXX object lib/CMakeFiles/gnuradio-radar.dir/estimator_fsk_impl.cc.o
[ 40%] Building CXX object lib/CMakeFiles/gnuradio-radar.dir/usrp_echotimer_cc_impl.cc.o
[ 42%] Building CXX object lib/CMakeFiles/gnuradio-radar.dir/estimator_fmcw_impl.cc.o
[ 44%] Building CXX object lib/CMakeFiles/gnuradio-radar.dir/signal_generator_sync_pulse_c_impl.cc.o
[ 46%] Building CXX object lib/CMakeFiles/gnuradio-radar.dir/estimator_sync_pulse_c_impl.cc.o
[ 48%] Building CXX object lib/CMakeFiles/gnuradio-radar.dir/find_max_peak_c_impl.cc.o
[ 50%] Building CXX object lib/CMakeFiles/gnuradio-radar.dir/qtgui_scatter_plot_impl.cc.o
[ 51%] Building CXX object lib/CMakeFiles/gnuradio-radar.dir/qtgui_time_plot_impl.cc.o
[ 53%] Building CXX object lib/CMakeFiles/gnuradio-radar.dir/tracking_singletarget_impl.cc.o
[ 55%] Building CXX object lib/CMakeFiles/gnuradio-radar.dir/msg_gate_impl.cc.o
[ 57%] Building CXX object lib/CMakeFiles/gnuradio-radar.dir/msg_manipulator_impl.cc.o
[ 59%] Building CXX object lib/CMakeFiles/gnuradio-radar.dir/ofdm_cyclic_prefix_remover_cvc_impl.cc.o
[ 61%] Building CXX object lib/CMakeFiles/gnuradio-radar.dir/transpose_matrix_vcvc_impl.cc.o
[ 63%] Building CXX object lib/CMakeFiles/gnuradio-radar.dir/qtgui_spectrogram_plot_impl.cc.o
[ 65%] Building CXX object lib/CMakeFiles/gnuradio-radar.dir/crop_matrix_vcvc_impl.cc.o
[ 67%] Building CXX object lib/CMakeFiles/gnuradio-radar.dir/ofdm_divide_vcvc_impl.cc.o
[ 69%] Building CXX object lib/CMakeFiles/gnuradio-radar.dir/os_cfar_2d_vc_impl.cc.o
[ 71%] Building CXX object lib/CMakeFiles/gnuradio-radar.dir/estimator_ofdm_impl.cc.o
[ 73%] Building CXX object lib/CMakeFiles/gnuradio-radar.dir/estimator_rcs_impl.cc.o
[ 75%] Building CXX object lib/CMakeFiles/gnuradio-radar.dir/trigger_command_impl.cc.o
make[2]: stat: /usr/local/lib/libqwt.so: 符号连接的层数过多
make[2]: *** No rule to make target '/usr/local/lib/libqwt.so', needed by 'lib/libgnuradio-radar.so'。 停止。
CMakeFiles/Makefile2:123: recipe for target 'lib/CMakeFiles/gnuradio-radar.dir/all' failed
make[1]: *** [lib/CMakeFiles/gnuradio-radar.dir/all] Error 2
Makefile:123: recipe for target 'all' failed
make: *** [all] Error 2

and here is my **cmake** log:

pelsor@pelsor-N550JK:~/gr-radar/build$ cmake ..
-- The CXX compiler identification is GNU 4.9.1
-- The C compiler identification is GNU 4.9.1
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Build type not specified: defaulting to release.
-- Boost version: 1.60.0
-- Found the following Boost libraries:
--   filesystem
--   system
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.28") 
-- checking for module 'cppunit'
--   found cppunit, version 1.13.2
-- Found CPPUNIT: /usr/lib/x86_64-linux-gnu/libcppunit.so;dl  
-- checking for module 'fftw3f >= 3.0'
--   found fftw3f , version 3.3.4
-- Found FFTW3F: /usr/lib/x86_64-linux-gnu/libfftw3f.so  
-- Looking for Q_WS_X11
-- Looking for Q_WS_X11 - found
-- Looking for Q_WS_WIN
-- Looking for Q_WS_WIN - not found
-- Looking for Q_WS_QWS
-- Looking for Q_WS_QWS - not found
-- Looking for Q_WS_MAC
-- Looking for Q_WS_MAC - not found
-- Found Qt4: /usr/bin/qmake-qt4 (found suitable version "4.8.6", minimum required is "4.2.0") 
-- QWT Version: 6.0.0
-- Found Qwt: /usr/local/lib/libqwt.so  
-- checking for module 'uhd'
--   found uhd, version 003.010.git-202-g9e0861e1
-- Found UHD: /usr/local/lib/libuhd.so  
Checking for GNU Radio Module: RUNTIME
-- checking for module 'gnuradio-runtime'
--   found gnuradio-runtime, version 3.7.9.2
 * INCLUDES=/usr/local/include
 * LIBS=/usr/local/lib/libgnuradio-runtime.so;/usr/local/lib/libgnuradio-pmt.so
-- Found GNURADIO_RUNTIME: /usr/local/lib/libgnuradio-runtime.so;/usr/local/lib/libgnuradio-pmt.so  
GNURADIO_RUNTIME_FOUND = TRUE
-- 
-- Checking for module SWIG
-- Found SWIG version 2.0.12.
-- Found SWIG: /usr/bin/swig2.0  
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython2.7.so (found suitable version "2.7.8", minimum required is "2") 
-- Found PythonInterp: /usr/bin/python2 (found suitable version "2.7.8", minimum required is "2") 
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of size_t
-- Check size of size_t - done
-- Check size of unsigned int
-- Check size of unsigned int - done
-- Check size of unsigned long
-- Check size of unsigned long - done
-- Check size of unsigned long long
-- Check size of unsigned long long - done
-- Performing Test HAVE_WNO_UNUSED_BUT_SET_VARIABLE
-- Performing Test HAVE_WNO_UNUSED_BUT_SET_VARIABLE - Success
-- Configuring done
-- Generating done
-- Build files have been written to: /home/pelsor/gr-radar/build

as far as I know,**my gnuradio version is  3.7.9.2** .**uhd version is 3.10**,**boost version is 1.60.0**.**qt version is 4.8.6**,"qwt version is 6.0.0",I think my qwt library was not installed correctly,so can anyone tell me how to solove the **make** error?

thankyou verymuch!!!

**Comment by stwunsch** [comment]
I think you have messed up gnuradio installation. Check these things:

- You need a source build of gnuradio, apt-get won't work!
- If you build it from source, you have to install the correct qwt version *before*. Only then, gnuradio uses the correct library.
- You need to build the software this way: First uhd, then gnuradio and then gr-radar. Otherwise, you can use pybombs as well (github.com/gnuradio/pybombs).
