### ISSUE TITLE
Error when run "cmake .." and "make"

### ISSUE THREAD

**Issue by hithuaiyuan** [kit-cel/gr-radar#14]
when I run cmake .. the Error is below:
-- Build type not specified: defaulting to release.
-- QWT Version: 6.0.0
Checking for GNU Radio Module: RUNTIME
 * INCLUDES=/usr/local/include
 * LIBS=/usr/local/lib/libgnuradio-runtime.so;/usr/local/lib/libgnuradio-pmt.so
GNURADIO_RUNTIME_FOUND = TRUE
-- 
-- Checking for module SWIG
-- Found SWIG version 2.0.4.
-- Configuring done
CMake Error at /usr/share/cmake-2.8/Modules/Qt4Macros.cmake:118 (ADD_CUSTOM_COMMAND):
  Error evaluating generator expression:

    $<CONFIG:Debug>

  Expression syntax not recognized.
Call Stack (most recent call first):
  /usr/share/cmake-2.8/Modules/Qt4Macros.cmake:149 (QT4_CREATE_MOC_COMMAND)
  lib/CMakeLists.txt:27 (QT4_WRAP_CPP)

CMake Error at /usr/share/cmake-2.8/Modules/Qt4Macros.cmake:118 (ADD_CUSTOM_COMMAND):
  Error evaluating generator expression:

    $<CONFIG:Debug>

  Expression syntax not recognized.
Call Stack (most recent call first):
  /usr/share/cmake-2.8/Modules/Qt4Macros.cmake:149 (QT4_CREATE_MOC_COMMAND)
  lib/CMakeLists.txt:27 (QT4_WRAP_CPP)

CMake Error at /usr/share/cmake-2.8/Modules/Qt4Macros.cmake:118 (ADD_CUSTOM_COMMAND):
  Error evaluating generator expression:

    $<CONFIG:Debug>

  Expression syntax not recognized.
Call Stack (most recent call first):
  /usr/share/cmake-2.8/Modules/Qt4Macros.cmake:149 (QT4_CREATE_MOC_COMMAND)
  lib/CMakeLists.txt:27 (QT4_WRAP_CPP)

-- Generating done
-- Build files have been written to: /home/xiaojingling/gr-radar/build

and when run make , 

[  1%] Generating moc_spectrogram_plot.cxx
[  3%] Generating moc_scatter_plot.cxx
[  5%] Generating moc_time_plot.cxx
Scanning dependencies of target gnuradio-radar
[  7%] Building CXX object lib/CMakeFiles/gnuradio-radar.dir/moc_scatter_plot.cxx.o
<command-line>:0:4: warning: missing whitespace after the macro name [enabled by default]
[  9%] Building CXX object lib/CMakeFiles/gnuradio-radar.dir/moc_time_plot.cxx.o
<command-line>:0:4: warning: missing whitespace after the macro name [enabled by default]
[ 11%] Building CXX object lib/CMakeFiles/gnuradio-radar.dir/moc_spectrogram_plot.cxx.o
<command-line>:0:4: warning: missing whitespace after the macro name [enabled by default]
In file included from /home/owner/gr-radar-master/build/lib/moc_spectrogram_plot.cxx:10:0:
/home/owner/gr-radar-master/build/lib/../../lib/spectrogram_plot.h:30:36: fatal error: qwt_matrix_raster_data.h: No such file or directory
compilation terminated.
make[2]: *** [lib/CMakeFiles/gnuradio-radar.dir/moc_spectrogram_plot.cxx.o] Error 1
make[1]: *** [lib/CMakeFiles/gnuradio-radar.dir/all] Error 2
make: *** [all] Error 2

I don't know how to do with it...

**Comment by stwunsch** [comment]
Thank you very much for sharing this! Most likely I know what the problem is. I suppose that the changes in the FindQt4 Module aren't compatible with cmake 2.8. I'll check this and report soon.

**Comment by stwunsch** [comment]
I pushed a change to master. Please report whether it works for you again!

**Comment by hithuaiyuan** [comment]
thank you！I will have a try soon.

**Comment by hithuaiyuan** [comment]
Thank you very much! I have installed successfully!

**Comment by stwunsch** [comment]
np :)
