### ISSUE TITLE
Error while running Ctest

### ISSUE THREAD

**Issue by eddiedobled** [kit-cel/gr-radar#18]
hello. help me please.
i have two problems.

**93% test passed, 2 test failed out of 27

5 - qa_os_cfar_c (failed)
17 - qa_tracking_singletarget (failed)

Error while running Ctest**

**Comment by stwunsch** [comment]
Please run `ctest -V -R <regex>` with `<regex>`  set to `qa_os_cfar_c` and `qa_tracking_singletarget`. My first guess is that you missed to run the `setup_core` script?
