### ISSUE TITLE
need help,about ctest errors

### ISSUE THREAD

**Issue by skywalkerlk** [kit-cel/gr-radar#22]
Hi everyone,
I have installed qt-4.8.7,qwt6.0.0,also gnuradio,uhd vesion are right.When I download the  .zip file in /home,and unpack it,follow "mkdir build->cd build/->cmake ../->make->sudo ./../examples/setup/setup_core",when I run ctest,there are totally 26 errors.

When I run ctest -V + "some error test name", It reminds me "Segmentation fault",like below:

longkang@longkang-All-Series:~/gr-radar/gr-radar-master/build$ ctest -V -R qa_estimator_fmcw 
UpdateCTestConfiguration  from :/home/longkang/gr-radar/gr-radar-master/build/DartConfiguration.tcl
UpdateCTestConfiguration  from :/home/longkang/gr-radar/gr-radar-master/build/DartConfiguration.tcl
Test project /home/longkang/gr-radar/gr-radar-master/build
Constructing a list of tests
Done constructing a list of tests
Checking test dependency graph...
Checking test dependency graph end
test 13
    Start 13: qa_estimator_fmcw

13: Test command: /bin/sh "/home/longkang/gr-radar/gr-radar-master/build/python/qa_estimator_fmcw_test.sh"
13: Test timeout computed to be: 9.99988e+06
13: Segmentation fault
1/1 Test #13: qa_estimator_fmcw ................***Failed    0.14 sec

0% tests passed, 1 tests failed out of 1

Total Test time (real) =   0.14 sec

The following tests FAILED:
	 13 - qa_estimator_fmcw (Failed)
Errors while running CTest

**Can you give me some help?**

Plus info:
======after cmake ../ ================
-- The CXX compiler identification is GNU 5.4.0
-- The C compiler identification is GNU 5.4.0
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Build type not specified: defaulting to release.
-- Boost version: 1.60.0
-- Found the following Boost libraries:
--   filesystem
--   system
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- Checking for module 'cppunit'
--   Found cppunit, version 1.13.2
-- Found CPPUNIT: /usr/lib/x86_64-linux-gnu/libcppunit.so;dl  
-- Could NOT find Doxygen (missing:  DOXYGEN_EXECUTABLE) 
-- Checking for module 'fftw3f >= 3.0'
--   Found fftw3f , version 3.3.4
-- Found FFTW3F: /usr/lib/x86_64-linux-gnu/libfftw3f.so  
-- Looking for Q_WS_X11
-- Looking for Q_WS_X11 - found
-- Looking for Q_WS_WIN
-- Looking for Q_WS_WIN - not found
-- Looking for Q_WS_QWS
-- Looking for Q_WS_QWS - not found
-- Looking for Q_WS_MAC
-- Looking for Q_WS_MAC - not found
-- Found Qt4: /usr/bin/qmake (found suitable version "4.8.7", minimum required is "4.2.0") 
-- QWT Version: 6.0.0
-- Found Qwt: /usr/lib/libqwt.so (Required is at least version "6.0.0") 
-- Checking for module 'uhd'
--   Found uhd, version 003.009.002-0-unknown
-- Found UHD: /usr/lib/x86_64-linux-gnu/libuhd.so  
Checking for GNU Radio Module: RUNTIME
-- Checking for module 'gnuradio-runtime'
--   Found gnuradio-runtime, version 3.7.9
 * INCLUDES=/usr/include
 * LIBS=/usr/lib/x86_64-linux-gnu/libgnuradio-runtime.so;/usr/lib/x86_64-linux-gnu/libgnuradio-pmt.so
-- Found GNURADIO_RUNTIME: /usr/lib/x86_64-linux-gnu/libgnuradio-runtime.so;/usr/lib/x86_64-linux-gnu/libgnuradio-pmt.so  
GNURADIO_RUNTIME_FOUND = TRUE
-- 
-- Checking for module SWIG
-- Found SWIG version 3.0.11.
-- Found SWIG: /usr/local/bin/swig  
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython2.7.so (found suitable version "2.7.12", minimum required is "2") 
-- Found PythonInterp: /usr/bin/python2 (found suitable version "2.7.12", minimum required is "2") 
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of size_t
-- Check size of size_t - done
-- Check size of unsigned int
-- Check size of unsigned int - done
-- Performing Test HAVE_WNO_UNUSED_BUT_SET_VARIABLE
-- Performing Test HAVE_WNO_UNUSED_BUT_SET_VARIABLE - Success
-- Could NOT find Doxygen (missing:  DOXYGEN_EXECUTABLE) 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/longkang/gr-radar/gr-radar-master/build

========after make ===============

[ 68%] Building CXX object lib/CMakeFiles/gnuradio-radar.dir/trigger_command_impl.cc.o
[ 70%] Linking CXX shared library libgnuradio-radar.so
[ 70%] Built target gnuradio-radar
Scanning dependencies of target test-radar
[ 71%] Building CXX object lib/CMakeFiles/test-radar.dir/test_radar.cc.o
[ 73%] Building CXX object lib/CMakeFiles/test-radar.dir/qa_radar.cc.o
[ 75%] Linking CXX executable test-radar
[ 75%] Built target test-radar
Scanning dependencies of target radar_swig_swig_doc
[ 75%] Built target radar_swig_swig_doc
Scanning dependencies of target _radar_swig_swig_tag
[ 77%] Building CXX object swig/CMakeFiles/_radar_swig_swig_tag.dir/_radar_swig_swig_tag.cpp.o
[ 78%] Linking CXX executable _radar_swig_swig_tag
[ 78%] Built target _radar_swig_swig_tag
[ 80%] Generating radar_swig.tag
Scanning dependencies of target radar_swig_swig_2d0df
[ 82%] Building CXX object swig/CMakeFiles/radar_swig_swig_2d0df.dir/radar_swig_swig_2d0df.cpp.o
[ 84%] Linking CXX executable radar_swig_swig_2d0df
Swig source
[ 84%] Built target radar_swig_swig_2d0df
Scanning dependencies of target _radar_swig
[ 85%] Building CXX object swig/CMakeFiles/_radar_swig.dir/radar_swigPYTHON_wrap.cxx.o
[ 87%] Linking CXX shared module _radar_swig.so
[ 91%] Built target _radar_swig
Scanning dependencies of target pygen_swig_7c093
[ 92%] Generating radar_swig.pyc
[ 94%] Generating radar_swig.pyo
[ 96%] Built target pygen_swig_7c093
Scanning dependencies of target pygen_python_dc6d6
[ 98%] Generating __init__.pyc
[100%] Generating __init__.pyo
[100%] Built target pygen_python_dc6d6
Scanning dependencies of target pygen_apps_9a6dd
[100%] Built target pygen_apps_9a6dd
longkang@longkang-All-Series:~/gr-radar/gr-radar-master/build$ sudo ./../examples/setup/setup_core 
[sudo] longkang 的密码： 
net.core.rmem_max = 50000000
net.core.wmem_max = 1048576
kernel.shmmax = 2147483648

**Comment by cdelpmatos** [comment]
I'm having the same issue. have you been able to solve it?

**Comment by sbmueller** [comment]
I'm not sure what happens here, but a core dump would definitely help. Could you try to generate one according to http://stackoverflow.com/questions/17965/how-to-generate-a-core-dump-in-linux-when-a-process-gets-a-segmentation-fault?

**Comment by dfy888** [comment]
> Hi everyone,
> I have installed qt-4.8.7,qwt6.0.0,also gnuradio,uhd vesion are right.When I download the .zip file in /home,and unpack it,follow "mkdir build->cd build/->cmake ../->make->sudo ./../examples/setup/setup_core",when I run ctest,there are totally 26 errors.
> 
> When I run ctest -V + "some error test name", It reminds me "Segmentation fault",like below:
> 
> longkang@longkang-All-Series:~/gr-radar/gr-radar-master/build$ ctest -V -R qa_estimator_fmcw
> UpdateCTestConfiguration from :/home/longkang/gr-radar/gr-radar-master/build/DartConfiguration.tcl
> UpdateCTestConfiguration from :/home/longkang/gr-radar/gr-radar-master/build/DartConfiguration.tcl
> Test project /home/longkang/gr-radar/gr-radar-master/build
> Constructing a list of tests
> Done constructing a list of tests
> Checking test dependency graph...
> Checking test dependency graph end
> test 13
> Start 13: qa_estimator_fmcw
> 
> 13: Test command: /bin/sh "/home/longkang/gr-radar/gr-radar-master/build/python/qa_estimator_fmcw_test.sh"
> 13: Test timeout computed to be: 9.99988e+06
> 13: Segmentation fault
> 1/1 Test #13: qa_estimator_fmcw ................***Failed 0.14 sec
> 
> 0% tests passed, 1 tests failed out of 1
> 
> Total Test time (real) = 0.14 sec
> 
> The following tests FAILED:
> 13 - qa_estimator_fmcw (Failed)
> Errors while running CTest
> 
> **Can you give me some help?**
> 
> Plus info:
> ======after cmake ../ ================
> -- The CXX compiler identification is GNU 5.4.0
> -- The C compiler identification is GNU 5.4.0
> -- Check for working CXX compiler: /usr/bin/c++
> -- Check for working CXX compiler: /usr/bin/c++ -- works
> -- Detecting CXX compiler ABI info
> -- Detecting CXX compiler ABI info - done
> -- Detecting CXX compile features
> -- Detecting CXX compile features - done
> -- Check for working C compiler: /usr/bin/cc
> -- Check for working C compiler: /usr/bin/cc -- works
> -- Detecting C compiler ABI info
> -- Detecting C compiler ABI info - done
> -- Detecting C compile features
> -- Detecting C compile features - done
> -- Build type not specified: defaulting to release.
> -- Boost version: 1.60.0
> -- Found the following Boost libraries:
> -- filesystem
> -- system
> -- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1")
> -- Checking for module 'cppunit'
> -- Found cppunit, version 1.13.2
> -- Found CPPUNIT: /usr/lib/x86_64-linux-gnu/libcppunit.so;dl
> -- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE)
> -- Checking for module 'fftw3f >= 3.0'
> -- Found fftw3f , version 3.3.4
> -- Found FFTW3F: /usr/lib/x86_64-linux-gnu/libfftw3f.so
> -- Looking for Q_WS_X11
> -- Looking for Q_WS_X11 - found
> -- Looking for Q_WS_WIN
> -- Looking for Q_WS_WIN - not found
> -- Looking for Q_WS_QWS
> -- Looking for Q_WS_QWS - not found
> -- Looking for Q_WS_MAC
> -- Looking for Q_WS_MAC - not found
> -- Found Qt4: /usr/bin/qmake (found suitable version "4.8.7", minimum required is "4.2.0")
> -- QWT Version: 6.0.0
> -- Found Qwt: /usr/lib/libqwt.so (Required is at least version "6.0.0")
> -- Checking for module 'uhd'
> -- Found uhd, version 003.009.002-0-unknown
> -- Found UHD: /usr/lib/x86_64-linux-gnu/libuhd.so
> Checking for GNU Radio Module: RUNTIME
> -- Checking for module 'gnuradio-runtime'
> -- Found gnuradio-runtime, version 3.7.9
> 
> * INCLUDES=/usr/include
> * LIBS=/usr/lib/x86_64-linux-gnu/libgnuradio-runtime.so;/usr/lib/x86_64-linux-gnu/libgnuradio-pmt.so
>   -- Found GNURADIO_RUNTIME: /usr/lib/x86_64-linux-gnu/libgnuradio-runtime.so;/usr/lib/x86_64-linux-gnu/libgnuradio-pmt.so
>   GNURADIO_RUNTIME_FOUND = TRUE
>   --
>   -- Checking for module SWIG
>   -- Found SWIG version 3.0.11.
>   -- Found SWIG: /usr/local/bin/swig
>   -- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython2.7.so (found suitable version "2.7.12", minimum required is "2")
>   -- Found PythonInterp: /usr/bin/python2 (found suitable version "2.7.12", minimum required is "2")
>   -- Looking for sys/types.h
>   -- Looking for sys/types.h - found
>   -- Looking for stdint.h
>   -- Looking for stdint.h - found
>   -- Looking for stddef.h
>   -- Looking for stddef.h - found
>   -- Check size of size_t
>   -- Check size of size_t - done
>   -- Check size of unsigned int
>   -- Check size of unsigned int - done
>   -- Performing Test HAVE_WNO_UNUSED_BUT_SET_VARIABLE
>   -- Performing Test HAVE_WNO_UNUSED_BUT_SET_VARIABLE - Success
>   -- Could NOT find Doxygen (missing:  DOXYGEN_EXECUTABLE)
>   -- Configuring done
>   -- Generating done
>   -- Build files have been written to: /home/longkang/gr-radar/gr-radar-master/build
> 
> ========after make ===============
> 
> [ 68%] Building CXX object lib/CMakeFiles/gnuradio-radar.dir/trigger_command_impl.cc.o
> [ 70%] Linking CXX shared library libgnuradio-radar.so
> [ 70%] Built target gnuradio-radar
> Scanning dependencies of target test-radar
> [ 71%] Building CXX object lib/CMakeFiles/test-radar.dir/test_radar.cc.o
> [ 73%] Building CXX object lib/CMakeFiles/test-radar.dir/qa_radar.cc.o
> [ 75%] Linking CXX executable test-radar
> [ 75%] Built target test-radar
> Scanning dependencies of target radar_swig_swig_doc
> [ 75%] Built target radar_swig_swig_doc
> Scanning dependencies of target _radar_swig_swig_tag
> [ 77%] Building CXX object swig/CMakeFiles/_radar_swig_swig_tag.dir/_radar_swig_swig_tag.cpp.o
> [ 78%] Linking CXX executable _radar_swig_swig_tag
> [ 78%] Built target _radar_swig_swig_tag
> [ 80%] Generating radar_swig.tag
> Scanning dependencies of target radar_swig_swig_2d0df
> [ 82%] Building CXX object swig/CMakeFiles/radar_swig_swig_2d0df.dir/radar_swig_swig_2d0df.cpp.o
> [ 84%] Linking CXX executable radar_swig_swig_2d0df
> Swig source
> [ 84%] Built target radar_swig_swig_2d0df
> Scanning dependencies of target _radar_swig
> [ 85%] Building CXX object swig/CMakeFiles/_radar_swig.dir/radar_swigPYTHON_wrap.cxx.o
> [ 87%] Linking CXX shared module _radar_swig.so
> [ 91%] Built target _radar_swig
> Scanning dependencies of target pygen_swig_7c093
> [ 92%] Generating radar_swig.pyc
> [ 94%] Generating radar_swig.pyo
> [ 96%] Built target pygen_swig_7c093
> Scanning dependencies of target pygen_python_dc6d6
> [ 98%] Generating **init**.pyc
> [100%] Generating **init**.pyo
> [100%] Built target pygen_python_dc6d6
> Scanning dependencies of target pygen_apps_9a6dd
> [100%] Built target pygen_apps_9a6dd
> longkang@longkang-All-Series:~/gr-radar/gr-radar-master/build$ sudo ./../examples/setup/setup_core
> [sudo] longkang 的密码：
> net.core.rmem_max = 50000000
> net.core.wmem_max = 1048576
> kernel.shmmax = 2147483648

I'm having the same issue. have you been able to solve it?    please help me!
