### ISSUE TITLE
Showing an error while executing an example flow graph (test_uhd_sink_source_inbuild.grc)

### ISSUE THREAD

**Issue by ff1016** [kit-cel/gr-radar#30]
I have a problem with 'OS-CFAR' from gr-radar toolbox. I have executed an example flowgraph to understand the properties of the OS-CFAR block. Unfortunately, it is showing an error.

<<< Welcome to GNU Radio Companion 3.7.11.1 >>>

Block paths:
    /home/wslsensor3/.grc_gnuradio
    /usr/local/share/gnuradio/grc/blocks

Loading: "/home/wslsensor3/Desktop/Dropbox/Practice/grc files/test_uhd_sink_source_inbuild.grc"
>>> Done

Generating: '/home/wslsensor3/Desktop/Dropbox/Practice/grc files/test_uhd_sink_source_inbuild.py'
>>> Warning: This flow graph may not have flow control: no audio or RF hardware blocks found. Add a Misc->Throttle block to your flow graph to avoid CPU congestion.

Executing: /usr/bin/python2 -u /home/wslsensor3/Desktop/Dropbox/Practice/grc files/test_uhd_sink_source_inbuild.py

Traceback (most recent call last):
  File "/home/wslsensor3/Desktop/Dropbox/Practice/grc files/test_uhd_sink_source_inbuild.py", line 172, in <module>
    main()
  File "/home/wslsensor3/Desktop/Dropbox/Practice/grc files/test_uhd_sink_source_inbuild.py", line 160, in main
    tb = top_block_cls()
  File "/home/wslsensor3/Desktop/Dropbox/Practice/grc files/test_uhd_sink_source_inbuild.py", line 72, in __init__
    self.radar_ts_fft_cc_0 = radar.ts_fft_cc(packet_len,  "packet_len")
AttributeError: 'module' object has no attribute 'ts_fft_cc'

>>> Done

Would anyone be so kind as to let me know, How to solve this problem?

**Comment by Wireless-a11y** [comment]
Hello, has your problem been solved? I also encountered the same problem.

**Comment by dfy888** [comment]
AttributeError: module 'radar' has no attribute 'ts_fft_cc'

**Comment by Waightman** [comment]
6/5000
The reason is version mismatch
从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2020年4月13日 19:18
收件人: ***@***.***>
抄送: ***@***.***>
主题: Re: [kit-cel/gr-radar] Showing an error while executing an example flow graph (test_uhd_sink_source_inbuild.grc) (#30)


Hello, has your problem been solved? I also encountered the same problem.

―
