### ISSUE TITLE
Cmake error on Mac OSX-Mojave

### ISSUE THREAD

**Issue by dukane627** [kit-cel/gr-radar#32]
I need help with this cmake error; To my knowledge I have a version of QT installed that should be good, but for some reason I get this error when running cmake:

Macbook:build Airbook$ cmake ..
-- Build type not specified: defaulting to release.
CMake Deprecation Warning at CMakeLists.txt:47 (cmake_policy):
  The OLD behavior for policy CMP0026 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.

CMake Deprecation Warning at CMakeLists.txt:50 (cmake_policy):
  The OLD behavior for policy CMP0043 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.

CMake Deprecation Warning at CMakeLists.txt:53 (cmake_policy):
  The OLD behavior for policy CMP0045 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.

CMake Deprecation Warning at CMakeLists.txt:56 (cmake_policy):
  The OLD behavior for policy CMP0046 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.

-- Boost version: 1.66.0
-- Found the following Boost libraries:
--   filesystem
--   system
-- Found unsuitable Qt version "" from NOTFOUND
-- QWT Version: 5.2.3
Checking for GNU Radio Module: RUNTIME
 * INCLUDES=/opt/local/include
 * LIBS=/opt/local/lib/libgnuradio-runtime.dylib;/opt/local/lib/libgnuradio-pmt.dylib;/opt/local/lib/liblog4cpp.dylib
GNURADIO_RUNTIME_FOUND = TRUE
Qt QTGUI library not found.
Qt QTCORE library not found.
-- Found unsuitable Qt version "" from NOTFOUND
CMake Error at lib/CMakeLists.txt:29 (QT4_WRAP_CPP):
  Unknown CMake command "QT4_WRAP_CPP".

-- Configuring incomplete, errors occurred!
See also "/Users/Airbook/gr-radar/build/CMakeFiles/CMakeOutput.log".

**Comment by marcusmueller** [comment]
A lot of things have changed, and building against GR3.8 should work due to #41 now, including on OS X. If the problem persists, please do not hesitate to reopen bug!
