### ISSUE TITLE
Branch for PR: Port to GNU Radio 3.8 

### ISSUE THREAD

**Issue by primercuervo** [kit-cel/gr-radar#35]
Hi,

I have a fork that is ready for an eventual code review containing the change proposals for porting this OOT to work along with GNU Radio 3.8. These changes are located in the maint-3.8 branch of the following repository https://github.com/primercuervo/gr-radar . I'd like to PR this changes to the original repo.

However, I'd like to also follow the GNU Radio's development convention, and keep all-this-3.8 contained in their own branch. As I'd like to open a PR here, I could:
* open the PR against `master`, pay attention to eventual feedback and apply changes, and then just expect the code to be pushed manually to a newly created `maint-3.8` branch (which might result in a slight overhead).
* wait for a `maint-3.8` branch to be open in this repository, and then create the PR against it, which would (technically) allow the contention of the PR management to GitHub.

I'd be happy to continue this discussion :smile:  I'm sure many would benefit from a working version of this OOT with GNU Radio 3.8.

Cheers!
-Nico

**Comment by sbmueller** [comment]
Summoning @stwunsch @fwunsch @marcusmueller

**Comment by marcusmueller** [comment]
maint-3.8 exists now.
