### ISSUE TITLE
ctest throws ImportError: No module named radar_swig

### ISSUE THREAD

**Issue by IDex** [kit-cel/gr-radar#9]
After following the instructions and building without complaints ctest fails all but the first test.
Here is output of ctest -V
https://gist.github.com/IDex/14ad7e1b0ac3586fcbca

**Comment by stwunsch** [comment]
Did you compile gnuradio on your own? It's hard to tell you what is wrong with the ctest output. Swig is used to wrap the cpp libraries to python. Somewhere there sth went wrong. Probably try a ldconfig (unlikely that it helps)?

**Comment by IDex** [comment]
After recompiling the github version of gnuradio the issue was resolved, seems to have been unrelated to gr-radar.
